<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIzDUqhX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIzDUqhX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIzDUqhX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIzDUqhX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIzDUqhX\App_KernelDevDebugContainer([
    'container.build_hash' => 'IzDUqhX',
    'container.build_id' => '184a7411',
    'container.build_time' => 1678892031,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIzDUqhX');
