<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ2p7UEu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ2p7UEu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ2p7UEu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ2p7UEu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ2p7UEu\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z2p7UEu',
    'container.build_id' => 'cf8fe3ef',
    'container.build_time' => 1672178616,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ2p7UEu');
